data:
  url: "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
  target_column: "quality"
  test_size: 0.2
  random_state: 42

model:
  name: "RandomForestClassifier"
  params:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 5
    random_state: 42

mlflow:
  experiment_name: "wine-quality-classifier"
  tracking_uri: "file:./mlruns"

preprocessing:
  scale: true
  handle_missing: true